
/*
 * 
 */

package pureairflowers.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Apr 21 14:59:25 CEST 2011
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "PureAirFlowers", 
                  wsdlLocation = "http://localhost:9010/PureAirFlowers?wsdl",
                  targetNamespace = "http://clients.pureairflowers/") 
public class PureAirFlowers extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://clients.pureairflowers/", "PureAirFlowers");
    public final static QName PureAirFlowersClientsImplPort = new QName("http://clients.pureairflowers/", "PureAirFlowersClientsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9010/PureAirFlowers?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9010/PureAirFlowers?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PureAirFlowers(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PureAirFlowers(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PureAirFlowers() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PureAirFlowersClients
     */
    @WebEndpoint(name = "PureAirFlowersClientsImplPort")
    public PureAirFlowersClients getPureAirFlowersClientsImplPort() {
        return super.getPort(PureAirFlowersClientsImplPort, PureAirFlowersClients.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PureAirFlowersClients
     */
    @WebEndpoint(name = "PureAirFlowersClientsImplPort")
    public PureAirFlowersClients getPureAirFlowersClientsImplPort(WebServiceFeature... features) {
        return super.getPort(PureAirFlowersClientsImplPort, PureAirFlowersClients.class, features);
    }

}
