
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-07-08T11:01:25.096+02:00
 * Generated source version: 2.3.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "GlobalWeather",
                      portName = "GlobalWeatherSoap12",
                      targetNamespace = "http://www.webserviceX.NET",
                      wsdlLocation = "http://www.webservicex.net/globalweather.asmx?wsdl",
                      endpointInterface = "net.webservicex.GlobalWeatherSoap")
                      
public class GlobalWeatherSoapImpl implements GlobalWeatherSoap {

    private static final Logger LOG = Logger.getLogger(GlobalWeatherSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherSoap#getCitiesByCountry(java.lang.String  countryName )*
     */
    public java.lang.String getCitiesByCountry(java.lang.String countryName) { 
        LOG.info("Executing operation getCitiesByCountry");
        System.out.println(countryName);
        try {
            java.lang.String _return = "_return2053838060";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherSoap#getWeather(java.lang.String  cityName ,)java.lang.String  countryName )*
     */
    public java.lang.String getWeather(java.lang.String cityName,java.lang.String countryName) { 
        LOG.info("Executing operation getWeather");
        System.out.println(cityName);
        System.out.println(countryName);
        try {
            java.lang.String _return = "_return1916903618";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
