/**
 * EasySOA Samples - Smart Travel
 * Copyright 2011 Open Wide
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact : easysoa-dev@groups.google.com
 */

package de.daenet.webservices.currencyserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue May 19 16:39:17 CEST 2009
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", name = "CurrencyServerWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CurrencyServerWebServiceSoap {

    @WebResult(name = "getDollarValueResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getDollarValue", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetDollarValue")
    @ResponseWrapper(localName = "getDollarValueResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetDollarValueResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getDollarValue")
    public double getDollarValue(
        @WebParam(name = "provider", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String provider,
        @WebParam(name = "currency", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String currency
    );

    @WebResult(name = "getProviderTimestampResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getProviderTimestamp", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetProviderTimestamp")
    @ResponseWrapper(localName = "getProviderTimestampResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetProviderTimestampResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getProviderTimestamp")
    public java.lang.String getProviderTimestamp(
        @WebParam(name = "providerId", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String providerId,
        @WebParam(name = "provider", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String provider
    );

    @WebResult(name = "getProviderListResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getProviderList", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetProviderList")
    @ResponseWrapper(localName = "getProviderListResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetProviderListResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getProviderList")
    public java.lang.String getProviderList();

    @WebResult(name = "getDataSetResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getDataSet", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetDataSet")
    @ResponseWrapper(localName = "getDataSetResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetDataSetResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getDataSet")
    public de.daenet.webservices.currencyserver.GetDataSetResponse.GetDataSetResult getDataSet(
        @WebParam(name = "provider", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String provider
    );

    @WebResult(name = "getXmlStreamResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getXmlStream", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetXmlStream")
    @ResponseWrapper(localName = "getXmlStreamResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetXmlStreamResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getXmlStream")
    public java.lang.String getXmlStream(
        @WebParam(name = "provider", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String provider
    );

    @WebResult(name = "getCurrencyValueResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getCurrencyValue", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetCurrencyValue")
    @ResponseWrapper(localName = "getCurrencyValueResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetCurrencyValueResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getCurrencyValue")
    public double getCurrencyValue(
        @WebParam(name = "provider", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String provider,
        @WebParam(name = "srcCurrency", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String srcCurrency,
        @WebParam(name = "dstCurrency", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String dstCurrency
    );

    @WebResult(name = "getProviderDescriptionResult", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
    @RequestWrapper(localName = "getProviderDescription", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetProviderDescription")
    @ResponseWrapper(localName = "getProviderDescriptionResponse", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer", className = "de.daenet.webservices.currencyserver.GetProviderDescriptionResponse")
    @WebMethod(action = "http://www.daenet.de/webservices/CurrencyServer/getProviderDescription")
    public java.lang.String getProviderDescription(
        @WebParam(name = "provider", targetNamespace = "http://www.daenet.de/webservices/CurrencyServer")
        java.lang.String provider
    );
}
