
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.daenet.webservices.currencyserver;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-07-20T14:27:53.459+02:00
 * Generated source version: 2.3.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CurrencyServerWebService",
                      portName = "CurrencyServerWebServiceHttpGet",
                      targetNamespace = "http://www.daenet.de/webservices/CurrencyServer",
                      wsdlLocation = "http://www.currencyserver.de/webservice/currencyserverwebservice.asmx?wsdl",
                      endpointInterface = "de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet")
                      
public class CurrencyServerWebServiceHttpGetImpl implements CurrencyServerWebServiceHttpGet {

    private static final Logger LOG = Logger.getLogger(CurrencyServerWebServiceHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getDollarValue(java.lang.String  provider ,)java.lang.String  currency )*
     */
    public double getDollarValue(java.lang.String provider,java.lang.String currency) { 
        LOG.info("Executing operation getDollarValue");
        System.out.println(provider);
        System.out.println(currency);
        try {
            double _return = 0.031949092815277136;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getProviderTimestamp(java.lang.String  providerId ,)java.lang.String  provider )*
     */
    public java.lang.String getProviderTimestamp(java.lang.String providerId,java.lang.String provider) { 
        LOG.info("Executing operation getProviderTimestamp");
        System.out.println(providerId);
        System.out.println(provider);
        try {
            java.lang.String _return = "_return612376777";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getProviderList(*
     */
    public java.lang.String getProviderList() { 
        LOG.info("Executing operation getProviderList");
        try {
            java.lang.String _return = "_return-1724966228";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getDataSet(java.lang.String  provider )*
     */
    public de.daenet.webservices.currencyserver.DataSet getDataSet(java.lang.String provider) { 
        LOG.info("Executing operation getDataSet");
        System.out.println(provider);
        try {
            de.daenet.webservices.currencyserver.DataSet _return = new de.daenet.webservices.currencyserver.DataSet();
            java.lang.Object _returnAny = null;
            _return.setAny(_returnAny);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getXmlStream(java.lang.String  provider )*
     */
    public java.lang.String getXmlStream(java.lang.String provider) { 
        LOG.info("Executing operation getXmlStream");
        System.out.println(provider);
        try {
            java.lang.String _return = "_return-1498392494";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getCurrencyValue(java.lang.String  provider ,)java.lang.String  srcCurrency ,)java.lang.String  dstCurrency )*
     */
    public double getCurrencyValue(java.lang.String provider,java.lang.String srcCurrency,java.lang.String dstCurrency) { 
        LOG.info("Executing operation getCurrencyValue");
        System.out.println(provider);
        System.out.println(srcCurrency);
        System.out.println(dstCurrency);
        try {
            double _return = 0.33901785444685706;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.daenet.webservices.currencyserver.CurrencyServerWebServiceHttpGet#getProviderDescription(java.lang.String  provider )*
     */
    public java.lang.String getProviderDescription(java.lang.String provider) { 
        LOG.info("Executing operation getProviderDescription");
        System.out.println(provider);
        try {
            java.lang.String _return = "_return-333115164";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
