
package org.talend.services.esb.locator.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-10-18T16:20:08.063+02:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "InterruptionFaultDetail", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
public class InterruptedExceptionFault extends Exception {
    
    private org.talend.schemas.esb.locator._2011._11.InterruptionFaultDetail interruptionFaultDetail;

    public InterruptedExceptionFault() {
        super();
    }
    
    public InterruptedExceptionFault(String message) {
        super(message);
    }
    
    public InterruptedExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InterruptedExceptionFault(String message, org.talend.schemas.esb.locator._2011._11.InterruptionFaultDetail interruptionFaultDetail) {
        super(message);
        this.interruptionFaultDetail = interruptionFaultDetail;
    }

    public InterruptedExceptionFault(String message, org.talend.schemas.esb.locator._2011._11.InterruptionFaultDetail interruptionFaultDetail, Throwable cause) {
        super(message, cause);
        this.interruptionFaultDetail = interruptionFaultDetail;
    }

    public org.talend.schemas.esb.locator._2011._11.InterruptionFaultDetail getFaultInfo() {
        return this.interruptionFaultDetail;
    }
}
