
package org.talend.services.esb.locator.v1;

import javax.xml.ws.Endpoint;

import org.easysoa.proxy.cxflocator.DiscoveryProxyLocatorServiceImpl;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-10-18T16:20:08.094+02:00
 * Generated source version: 2.4.1
 * 
 */
 
public class LocatorService_LocatorServiceSoap_Server{

    protected LocatorService_LocatorServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new DiscoveryProxyLocatorServiceImpl();
        String address = "http://localhost:8040/services/ServiceLocatorService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new LocatorService_LocatorServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
