package org.talend.services.esb.locator.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-10-18T16:20:08.072+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://www.talend.org/services/esb/locator/v1", name = "LocatorService")
@XmlSeeAlso({org.talend.schemas.esb.locator._2011._11.ObjectFactory.class})
public interface LocatorService {

    @RequestWrapper(localName = "unregisterEndpoint", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11", className = "org.talend.schemas.esb.locator._2011._11.UnregisterEndpoint")
    @WebMethod(action = "unregisterEndpoint")
    @ResponseWrapper(localName = "unregisterEndpointResponse", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11", className = "org.talend.schemas.esb.locator._2011._11.UnregisterEndpointResponse")
    public void unregisterEndpoint(
        @WebParam(name = "serviceName", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "endpointURL", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        java.lang.String endpointURL
    ) throws ServiceLocatorFault, InterruptedExceptionFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "lookupEndpointResponse", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11", partName = "parameters")
    @WebMethod(action = "lookupEndpoint")
    public org.talend.schemas.esb.locator._2011._11.LookupEndpointResponse lookupEndpoint(
        @WebParam(partName = "parameters", name = "lookupEndpoint", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        org.talend.schemas.esb.locator._2011._11.LookupRequestType parameters
    ) throws ServiceLocatorFault, InterruptedExceptionFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LookupEndpointsResponse", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11", partName = "parameters")
    @WebMethod(action = "lookupEndpoints")
    public org.talend.schemas.esb.locator._2011._11.LookupEndpointsResponse lookupEndpoints(
        @WebParam(partName = "parameters", name = "lookupEndpoints", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        org.talend.schemas.esb.locator._2011._11.LookupRequestType parameters
    ) throws ServiceLocatorFault, InterruptedExceptionFault;

    @RequestWrapper(localName = "registerEndpoint", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11", className = "org.talend.schemas.esb.locator._2011._11.RegisterEndpoint")
    @WebMethod(action = "registerEndpoint")
    @ResponseWrapper(localName = "registerEndpointResponse", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11", className = "org.talend.schemas.esb.locator._2011._11.RegisterEndpointResponse")
    public void registerEndpoint(
        @WebParam(name = "serviceName", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        javax.xml.namespace.QName serviceName,
        @WebParam(name = "endpointURL", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        java.lang.String endpointURL,
        @WebParam(name = "binding", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        org.talend.schemas.esb.locator._2011._11.BindingType binding,
        @WebParam(name = "transport", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        org.talend.schemas.esb.locator._2011._11.TransportType transport,
        @WebParam(name = "properties", targetNamespace = "http://talend.org/schemas/esb/locator/2011/11")
        org.talend.schemas.esb.locator._2011._11.SLPropertiesType properties
    ) throws ServiceLocatorFault, InterruptedExceptionFault;
}
