
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.microsofttranslator.api.v1.soap_svc;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-07-22T18:52:21.945+02:00
 * Generated source version: 2.3.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "SoapService",
                      portName = "BasicHttpBinding_LanguageService",
                      targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc",
                      //wsdlLocation = "file:microsoftTranslatorWebService.test.wsdl",
                      endpointInterface = "com.microsofttranslator.api.v1.soap_svc.LanguageService")
                      
public class LanguageServiceImpl implements LanguageService {

    private static final Logger LOG = Logger.getLogger(LanguageServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.microsofttranslator.api.v1.soap_svc.LanguageService#detect(java.lang.String  appId ,)java.lang.String  text )*
     */
    public java.lang.String detect(java.lang.String appId,java.lang.String text) { 
        LOG.info("Executing operation detect");
        System.out.println(appId);
        System.out.println(text);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsofttranslator.api.v1.soap_svc.LanguageService#translate(java.lang.String  appId ,)java.lang.String  text ,)java.lang.String  from ,)java.lang.String  to )*
     */
    public java.lang.String translate(java.lang.String appId,java.lang.String text,java.lang.String from,java.lang.String to) { 
        LOG.info("Executing operation translate");
        System.out.println(appId);
        System.out.println(text);
        System.out.println(from);
        System.out.println(to);
        try {
            java.lang.String _return = "Je voudrais une biere !";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsofttranslator.api.v1.soap_svc.LanguageService#getLanguageNames(java.lang.String  appId ,)java.lang.String  locale )*
     */
    public com.microsofttranslator.api.v1.soap.ArrayOfstring getLanguageNames(java.lang.String appId,java.lang.String locale) { 
        LOG.info("Executing operation getLanguageNames");
        System.out.println(appId);
        System.out.println(locale);
        try {
            com.microsofttranslator.api.v1.soap.ArrayOfstring _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.microsofttranslator.api.v1.soap_svc.LanguageService#getLanguages(java.lang.String  appId )*
     */
    public com.microsofttranslator.api.v1.soap.ArrayOfstring getLanguages(java.lang.String appId) { 
        LOG.info("Executing operation getLanguages");
        System.out.println(appId);
        try {
            com.microsofttranslator.api.v1.soap.ArrayOfstring _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
