/**
 * EasySOA Samples - Smart Travel
 * Copyright 2011 Open Wide
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact : easysoa-dev@googlegroups.com
 */

package fr.inria.galaxy.j1.scenario1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.1
 * Thu May 21 20:15:22 CEST 2009
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://scenario1.j1.galaxy.inria.fr/", name = "ISummaryServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ISummaryServicePortType {

    @WebResult(name = "return", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
    @RequestWrapper(localName = "summarize", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/", className = "fr.inria.galaxy.j1.scenario1.Summarize")
    @ResponseWrapper(localName = "summarizeResponse", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/", className = "fr.inria.galaxy.j1.scenario1.SummarizeResponse")
    @WebMethod
    public java.lang.String summarize(
        @WebParam(name = "arg0", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
        double arg3,
        @WebParam(name = "arg4", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "http://scenario1.j1.galaxy.inria.fr/")
        java.lang.String arg5
    );
}
