
package org.openwide.easysoa.test.mock.meteomock.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-01-06T18:35:22.602+01:00
 * Generated source version: 2.4.1
 * 
 */
public final class MeteoMockPortType_MeteoMockPort_Client {

    private static final QName SERVICE_NAME = new QName("http://meteomock.mock.test.easysoa.openwide.org/", "MeteoMock");

    private MeteoMockPortType_MeteoMockPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MeteoMock.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MeteoMock ss = new MeteoMock(wsdlURL, SERVICE_NAME);
        MeteoMockPortType port = ss.getMeteoMockPort();  
        
        {
        System.out.println("Invoking getTomorrowForecast...");
        java.lang.String _getTomorrowForecast_arg0 = "";
        java.lang.String _getTomorrowForecast__return = port.getTomorrowForecast(_getTomorrowForecast_arg0);
        System.out.println("getTomorrowForecast.result=" + _getTomorrowForecast__return);


        }

        System.exit(0);
    }

}
