package pureairflowers.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Apr 21 14:59:25 CEST 2011
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://clients.pureairflowers/", name = "PureAirFlowersClients")
@XmlSeeAlso({ObjectFactory.class})
public interface PureAirFlowersClients {

    @WebResult(name = "ordersNumber", targetNamespace = "")
    @RequestWrapper(localName = "getOrdersNumber", targetNamespace = "http://clients.pureairflowers/", className = "pureairflowers.clients.GetOrdersNumber")
    @ResponseWrapper(localName = "getOrdersNumberResponse", targetNamespace = "http://clients.pureairflowers/", className = "pureairflowers.clients.GetOrdersNumberResponse")
    @WebMethod
    public int getOrdersNumber(
        @WebParam(name = "ClientId", targetNamespace = "")
        java.lang.String clientId
    );
}
