/**
 * EasySOA Registry
 * Copyright 2011 Open Wide
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact : easysoa-dev@googlegroups.com
 */

package org.easysoa.preview;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import org.nuxeo.common.utils.FileUtils;
import org.easysoa.preview.WSDLTransformer;

import junit.framework.TestCase;

public class TestXSLT extends TestCase {

    public void testXSLT() throws Exception {
        InputStream xmlStream = this.getClass().getResourceAsStream("/wsdl/nuxeoremoting.wsdl");
        assertNotNull(xmlStream);
        File out = File.createTempFile("out", ".html");
        OutputStream outStream = new FileOutputStream(out, false);
        WSDLTransformer.generateHtmlView(xmlStream, outStream);
        String html = FileUtils.readFile(out);
        assertTrue(html.contains("This page has been generated by <big>wsdl-viewer.xsl</big>"));
        out.delete();
    }

}
