package org.easysoa.preview;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import org.nuxeo.common.utils.FileUtils;
import org.easysoa.preview.WSDLTransformer;

import junit.framework.TestCase;

public class TestXSLT extends TestCase {

    public void testXSLT() throws Exception {
        InputStream xmlStream = this.getClass().getResourceAsStream("/wsdl/nuxeoremoting.wsdl");
        assertNotNull(xmlStream);
        File out = new File(System.getProperty("java.io.tmpdir"), "out.html");
        out.createNewFile();
        OutputStream outStream = new FileOutputStream(out, false);
        WSDLTransformer.generateHtmlView(xmlStream, outStream);
        String html = FileUtils.readFile(out);
        assertTrue(html.contains("This page has been generated by <big>wsdl-viewer.xsl</big>"));
        out.delete();
    }

}
