/**
 * EasySOA Proxy
 * Copyright 2011 Open Wide
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact : easysoa-dev@googlegroups.com
 */

package org.easysoa.test.mock.meteomock.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-01-06T18:35:22.664+01:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "MeteoMock", 
                  wsdlLocation = "http://localhost:8085/meteo?wsdl",
                  targetNamespace = "http://meteomock.mock.test.easysoa.openwide.org/") 
public class MeteoMock extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://meteomock.mock.test.easysoa.openwide.org/", "MeteoMock");
    public final static QName MeteoMockPort = new QName("http://meteomock.mock.test.easysoa.openwide.org/", "MeteoMockPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/meteo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MeteoMock.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/meteo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MeteoMock(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MeteoMock(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeteoMock() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MeteoMock(WebServiceFeature ... features) {
    	super(WSDL_LOCATION, SERVICE);
    	//super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MeteoMock(URL wsdlLocation, WebServiceFeature ... features) {
    	super(wsdlLocation, SERVICE);
    	//super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MeteoMock(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        //super(wsdlLocation, serviceName, features);
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns MeteoMockPortType
     */
    @WebEndpoint(name = "MeteoMockPort")
    public MeteoMockPortType getMeteoMockPort() {
        return super.getPort(MeteoMockPort, MeteoMockPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeteoMockPortType
     */
    @WebEndpoint(name = "MeteoMockPort")
    public MeteoMockPortType getMeteoMockPort(WebServiceFeature... features) {
        return super.getPort(MeteoMockPort, MeteoMockPortType.class, features);
    }

}
