package org.talend.esb.sam.server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.talend.esb.sam.monitoringservice.v1.MonitoringService;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-09-26T17:41:14.442+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "MonitoringWebServiceService", 
                  wsdlLocation = "http://localhost:8080/sam-server-war/services/MonitoringServiceSOAP?wsdl",
                  targetNamespace = "http://service.server.sam.esb.talend.org/") 
public class MonitoringWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.server.sam.esb.talend.org/", "MonitoringWebServiceService");
    public final static QName MonitoringWebServicePort = new QName("http://service.server.sam.esb.talend.org/", "MonitoringWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/sam-server-war/services/MonitoringServiceSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MonitoringWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/sam-server-war/services/MonitoringServiceSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MonitoringWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MonitoringWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitoringWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MonitoringService
     */
    @WebEndpoint(name = "MonitoringWebServicePort")
    public MonitoringService getMonitoringWebServicePort() {
        return super.getPort(MonitoringWebServicePort, MonitoringService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitoringService
     */
    @WebEndpoint(name = "MonitoringWebServicePort")
    public MonitoringService getMonitoringWebServicePort(WebServiceFeature... features) {
        return super.getPort(MonitoringWebServicePort, MonitoringService.class, features);
    }

}
