
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Nov 02 15:11:24 CET 2009
 * Generated source version: 2.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "GlobalWeather",
                      portName = "GlobalWeatherSoap",
                      targetNamespace = "http://www.webserviceX.NET",
                      //wsdlLocation = "meteo.wsdl",
                      endpointInterface = "net.webservicex.GlobalWeatherHttpGet")
                      
public class GlobalWeatherHttpGetImpl implements GlobalWeatherHttpGet {

    private static final Logger LOG = Logger.getLogger(GlobalWeatherHttpGetImpl.class.getName());

    private IGlobalWeather globalWeather = GlobalWeatherImpl.getInstance();
    
    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherHttpGet#getCitiesByCountry(java.lang.String  countryName )*
     */
    public java.lang.String getCitiesByCountry(java.lang.String countryName) { 
        LOG.info("Executing operation getCitiesByCountry");
        System.out.println(countryName);
        try {
            return globalWeather.getCitiesByCountry(countryName);
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherHttpGet#getWeather(java.lang.String  cityName ,)java.lang.String  countryName )*
     */
    public java.lang.String getWeather(java.lang.String cityName,java.lang.String countryName) { 
        LOG.info("Executing operation getWeather");
        System.out.println(cityName);
        System.out.println(countryName);
        try {
            return globalWeather.getWeather(cityName, countryName);
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
