
/*
 * 
 */

package fr.inria.galaxy.j1.scenario1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue May 26 17:11:22 CEST 2009
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "Trip", 
                  wsdlLocation = "file:GalaxyTrip.wsdl",
                  targetNamespace = "http://scenario1.j1.galaxy.inria.fr/") 
public class Trip extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://scenario1.j1.galaxy.inria.fr/", "Trip");
    public final static QName TripPort = new QName("http://scenario1.j1.galaxy.inria.fr/", "TripPort");
    static {
        URL url = null;
        try {
            url = new URL("file:GalaxyTrip.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:GalaxyTrip.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Trip(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Trip(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Trip() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TripPortType
     */
    @WebEndpoint(name = "TripPort")
    public TripPortType getTripPort() {
        return super.getPort(TripPort, TripPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TripPortType
     */
    @WebEndpoint(name = "TripPort")
    public TripPortType getTripPort(WebServiceFeature... features) {
        return super.getPort(TripPort, TripPortType.class, features);
    }

}
