package fr.inria.galaxy.demo.currency.client.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import javax.xml.namespace.QName;

import org.apache.cxf.configuration.jsse.TLSClientParameters;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;

import de.daenet.webservices.currencyserver.CurrencyServerWebService;
import de.daenet.webservices.currencyserver.CurrencyServerWebServiceSoap;

/**
 * This class was generated by Apache CXF 2.2.1 Tue Nov 03 12:16:13 CET 2009
 * Generated source version: 2.2.1
 * 
 */

public final class CurrencyServerClient {

	private static final QName SERVICE_NAME = new QName("http://www.daenet.de/webservices/CurrencyServer", "CurrencyServerWebService");

	private CurrencyServerClient() {
	}

	public static void main(String args[]) throws Exception {
		URL wsdlURL = CurrencyServerClient.class.getResource("/currencyserverwebservice.wsdl");
		
		CurrencyServerWebService ss = new CurrencyServerWebService(wsdlURL, SERVICE_NAME);
		CurrencyServerWebServiceSoap port = ss.getCurrencyServerWebServiceSoap();
		allowSSLConnection(port);

		{
			System.out.println("Invoking Euro to USD");
			System.out.println("Euro to USD:" + port.getCurrencyValue("3", "EUR", "USD"));
			System.out.println("USD to Euro:" + port.getCurrencyValue("3", "USD", "EUR"));
		}

		System.exit(0);
	}

	private static void allowSSLConnection(Object service) {
		Client clientProxy = ClientProxy.getClient(service);

		HTTPConduit conduit = (HTTPConduit) clientProxy.getConduit();
		String targetAddr = conduit.getTarget().getAddress().getValue();
		if (targetAddr.toLowerCase().startsWith("https:")) {
			TrustManager[] simpleTrustManager = new TrustManager[] { new X509TrustManager() {
				public java.security.cert.X509Certificate[] getAcceptedIssuers() {
					return null;
				}

				public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType) {
				}

				public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType) {
				}
			} };
			TLSClientParameters tlsParams = new TLSClientParameters();
			tlsParams.setTrustManagers(simpleTrustManager);
			tlsParams.setDisableCNCheck(true);
			conduit.setTlsClientParameters(tlsParams);
		}
	}

}
