package com.microsofttranslator.api.v1.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Jun 27 12:18:25 CEST 2011
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", name = "LanguageService")
@XmlSeeAlso({ObjectFactory.class,com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface LanguageService {

    @WebResult(name = "DetectResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @Action(input = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Detect", output = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/DetectResponse")
    @RequestWrapper(localName = "Detect", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.Detect")
    @ResponseWrapper(localName = "DetectResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.DetectResponse")
    @WebMethod(operationName = "Detect", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Detect")
    public java.lang.String detect(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String text
    );

    @WebResult(name = "TranslateResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @Action(input = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Translate", output = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/TranslateResponse")
    @RequestWrapper(localName = "Translate", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.Translate")
    @ResponseWrapper(localName = "TranslateResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.TranslateResponse")
    @WebMethod(operationName = "Translate", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Translate")
    public java.lang.String translate(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String text,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String to
    );

    @WebResult(name = "GetLanguageNamesResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @Action(input = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNames", output = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNamesResponse")
    @RequestWrapper(localName = "GetLanguageNames", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguageNames")
    @ResponseWrapper(localName = "GetLanguageNamesResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguageNamesResponse")
    @WebMethod(operationName = "GetLanguageNames", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNames")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring getLanguageNames(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String appId,
        @WebParam(name = "locale", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String locale
    );

    @WebResult(name = "GetLanguagesResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @Action(input = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguages", output = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguagesResponse")
    @RequestWrapper(localName = "GetLanguages", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguages")
    @ResponseWrapper(localName = "GetLanguagesResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguagesResponse")
    @WebMethod(operationName = "GetLanguages", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguages")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring getLanguages(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        java.lang.String appId
    );
}
