
package de.sopera.airportsoap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-21T16:33:34.433+02:00
 * Generated source version: 2.4.1
 * 
 */
 
public class AirportSoap_AirportSoap_Server{

    protected AirportSoap_AirportSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new AirportSoapImpl();
        String address = "http://localhost:8200/esb/AirportService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new AirportSoap_AirportSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
