package de.sopera.airportsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-21T16:33:34.438+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "airport", 
                  wsdlLocation = "file:airport_soap.wsdl",
                  targetNamespace = "http://airportsoap.sopera.de") 
public class Airport extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://airportsoap.sopera.de", "airport");
    public final static QName AirportSoap = new QName("http://airportsoap.sopera.de", "airportSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:airport_soap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Airport.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:airport_soap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Airport(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Airport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Airport() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AirportSoap
     */
    @WebEndpoint(name = "airportSoap")
    public AirportSoap getAirportSoap() {
        return super.getPort(AirportSoap, AirportSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirportSoap
     */
    @WebEndpoint(name = "airportSoap")
    public AirportSoap getAirportSoap(WebServiceFeature... features) {
        return super.getPort(AirportSoap, AirportSoap.class, features);
    }

}
