package de.sopera.airportsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-21T16:33:34.390+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(serviceName="airport", portName="airportSoap", targetNamespace = "http://airportsoap.sopera.de", name = "airportSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AirportSoap {

    @WebResult(name = "getAirportInformationByISOCountryCodeResult", targetNamespace = "http://airportsoap.sopera.de")
    @RequestWrapper(localName = "getAirportInformationByISOCountryCode", targetNamespace = "http://airportsoap.sopera.de", className = "de.sopera.airportsoap.GetAirportInformationByISOCountryCode")
    @WebMethod(action = "http://airportsoap.sopera.de/getAirportInformationByISOCountryCode")
    @ResponseWrapper(localName = "getAirportInformationByISOCountryCodeResponse", targetNamespace = "http://airportsoap.sopera.de", className = "de.sopera.airportsoap.GetAirportInformationByISOCountryCodeResponse")
    public java.lang.String getAirportInformationByISOCountryCode(
        @WebParam(name = "CountryAbbrviation", targetNamespace = "http://airportsoap.sopera.de")
        java.lang.String countryAbbrviation
    );
}
