/**
 * 
 */
package org.easysoa.proxy.management;

//import org.easysoa.model.Application;
//import org.easysoa.model.User;
import org.easysoa.proxy.core.api.configuration.EasySOAGeneratedAppConfiguration;
import org.easysoa.proxy.registry.Template;

/**
 * @author jguillemotte
 *
 */
public class FraSCAtiStudioGeneratedAppService {

    /**
     * Generate and deploy an application using FraSCAti studio
     * @param id Application ID
     * @param template Template to use for generate the application composite
     * @param configuration The configuration parameters for the application
     * @return 
     */
    public String generateAndDeploy(String id, Template template, EasySOAGeneratedAppConfiguration configuration){
        //returns service (or id ?), .delete(id) (also removes from availablePorts),

        // Call FraSCAti studio create application method from ServiceManager
        // Parameters :
        // - user = user build from informations contained in appConfiguration 
        // - name = can be the app ID generated by idFactory from appConfiguration
        // - description = predefined desciption (maybe with a dynamic part as the appID) 
        // - package name = generated with the data contained in the appConfiguration
        // - template = template to use for generattion
        // - params = params contained in appConfiguration
        
        // How to get the generated Application object ?
        /*String message = createApplication(User user, String name, String description,
                String packageName, String templateName, Map<String, Object> params);*/        
        
        // Call FraSCati studio deploy method from org.easysoa.deploy.DeployProcessor
        // - ids : only the app ID here
        // - application : application generated by createApplication method call
        /*Boolean deployResult = deploy(String[] ids, Application application);*/
        
        // 
        
        return "";
    }
}
