# EasySOA build settings
#########################

# HOWTO
# - Copy this file or parts of this file to $HOME/.buildr/settings.yaml
# - Edit the settings at will (make sure Nuxeo and Node paths lead to a correct location)
# - Type "buildr help" from this folder to see what build commands you can use

nuxeo:
  path: 
  # To use for packaging. By default $HOME/nuxeo-cap-5.5-tomcat
  # Specify the path either absolute or relative to the buildfile.
  
talend-esb:
  path: 
  # To use for packaging, if you package EasySOA with the "withtalend" option.
  # By default $HOME/talend-esb. Specify the path either absolute or relative to the buildfile.
  
node:
  path:
  # To use for packaging (Linux version). By default /usr/local/bin/
  # Specify the path either absolute or relative to the buildfile.
  # TODO Download automatically
  
# Release configuration

release:
  version: '0.4-SNAPSHOT'
