package org.talend.esb.sam.monitoringservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-09-26T17:41:14.420+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.talend.org/esb/sam/MonitoringService/v1", name = "MonitoringService")
@XmlSeeAlso({ObjectFactory.class, org.talend.esb.sam._2011._03.common.ObjectFactory.class})
public interface MonitoringService {

    @WebResult(name = "successMessage", targetNamespace = "http://www.talend.org/esb/sam/2011/03/common")
    @RequestWrapper(localName = "putEvents", targetNamespace = "http://www.talend.org/esb/sam/MonitoringService/v1", className = "org.talend.esb.sam.monitoringservice.v1.PutEvents")
    @WebMethod(action = "http://www.talend.org/esb/sam/MonitoringService/v1/putEvents")
    @ResponseWrapper(localName = "putEventsResponse", targetNamespace = "http://www.talend.org/esb/sam/MonitoringService/v1", className = "org.talend.esb.sam._2011._03.common.SuccessType")
    public java.lang.String putEvents(
        @WebParam(name = "event", targetNamespace = "http://www.talend.org/esb/sam/MonitoringService/v1")
        java.util.List<org.talend.esb.sam._2011._03.common.EventType> event
    ) throws PutEventsFault;
}
