
package org.talend.esb.sam.monitoringservice.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-09-26T17:41:14.375+02:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "fault", targetNamespace = "http://www.talend.org/esb/sam/MonitoringService/v1")
public class PutEventsFault extends Exception {
    
    private org.talend.esb.sam._2011._03.common.FaultType fault;

    public PutEventsFault() {
        super();
    }
    
    public PutEventsFault(String message) {
        super(message);
    }
    
    public PutEventsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PutEventsFault(String message, org.talend.esb.sam._2011._03.common.FaultType fault) {
        super(message);
        this.fault = fault;
    }

    public PutEventsFault(String message, org.talend.esb.sam._2011._03.common.FaultType fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.talend.esb.sam._2011._03.common.FaultType getFaultInfo() {
        return this.fault;
    }
}
