/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openwide.easysoa.test.event.paf.test;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * WSDL2JAVA generated
 * This class was generated by Apache CXF 2.4.0
 * 2012-06-22T11:53:41.673+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://paf.samples.easysoa.org/", name = "PureAirFlowersService")
//@XmlSeeAlso({ObjectFactory.class})
public interface PureAirFlowersService {

    @WebResult(name = "addOrder", targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://paf.samples.easysoa.org/", className = "org.easysoa.samples.paf.AddOrder")
    @WebMethod
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://paf.samples.easysoa.org/", className = "org.easysoa.samples.paf.AddOrderResponse")
    public int addOrder(
        @WebParam(name = "orderNb", targetNamespace = "")
        java.lang.Integer orderNb,
        @WebParam(name = "ClientName", targetNamespace = "")
        java.lang.String clientName
    );

    @WebResult(name = "ordersNumber", targetNamespace = "")
    @RequestWrapper(localName = "getOrdersNumber", targetNamespace = "http://paf.samples.easysoa.org/", className = "org.easysoa.samples.paf.GetOrdersNumber")
    @WebMethod
    @ResponseWrapper(localName = "getOrdersNumberResponse", targetNamespace = "http://paf.samples.easysoa.org/", className = "org.easysoa.samples.paf.GetOrdersNumberResponse")
    public int getOrdersNumber(
        @WebParam(name = "ClientName", targetNamespace = "")
        java.lang.String clientName
    );
}