
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-07-08T11:01:25.034+02:00
 * Generated source version: 2.3.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "GlobalWeather",
                      portName = "GlobalWeatherHttpPost",
                      targetNamespace = "http://www.webserviceX.NET",
                      //wsdlLocation = "http://www.webservicex.net/globalweather.asmx?wsdl",
                      endpointInterface = "net.webservicex.GlobalWeatherHttpPost")
                      
public class GlobalWeatherHttpPostImpl implements GlobalWeatherHttpPost {

    private static final Logger LOG = Logger.getLogger(GlobalWeatherHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherHttpPost#getCitiesByCountry(java.lang.String  countryName )*
     */
    public java.lang.String getCitiesByCountry(java.lang.String countryName) { 
        LOG.info("Executing operation getCitiesByCountry");
        System.out.println(countryName);
        try {
            java.lang.String _return = "_return661855729";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherHttpPost#getWeather(java.lang.String  cityName ,)java.lang.String  countryName )*
     */
    public java.lang.String getWeather(java.lang.String cityName,java.lang.String countryName) { 
        LOG.info("Executing operation getWeather");
        System.out.println(cityName);
        System.out.println(countryName);
        try {
            java.lang.String _return = "_return1632216220";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
