
package com.microsofttranslator.api.v1.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LanguageService", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsofttranslator.api.v1.soap.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface LanguageService {


    /**
     * 
     * @param appId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetLanguages", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguages")
    @WebResult(name = "GetLanguagesResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @RequestWrapper(localName = "GetLanguages", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguages")
    @ResponseWrapper(localName = "GetLanguagesResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguagesResponse")
    public ArrayOfstring getLanguages(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String appId);

    /**
     * 
     * @param appId
     * @param locale
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetLanguageNames", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNames")
    @WebResult(name = "GetLanguageNamesResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @RequestWrapper(localName = "GetLanguageNames", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguageNames")
    @ResponseWrapper(localName = "GetLanguageNamesResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.GetLanguageNamesResponse")
    public ArrayOfstring getLanguageNames(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String appId,
        @WebParam(name = "locale", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String locale);

    /**
     * 
     * @param text
     * @param appId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Detect", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Detect")
    @WebResult(name = "DetectResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @RequestWrapper(localName = "Detect", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.Detect")
    @ResponseWrapper(localName = "DetectResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.DetectResponse")
    public String detect(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String text);

    /**
     * 
     * @param to
     * @param text
     * @param appId
     * @param from
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Translate", action = "http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Translate")
    @WebResult(name = "TranslateResult", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
    @RequestWrapper(localName = "Translate", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.Translate")
    @ResponseWrapper(localName = "TranslateResponse", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc", className = "com.microsofttranslator.api.v1.soap.TranslateResponse")
    public String translate(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String text,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/v1/soap.svc")
        String to);

}
